version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_cte
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSeguro123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

  backend:
    build: ./backend
    container_name: backend_cte
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlserver://db:1433;database=Centro_Tecnico_Electronico;user=sa;password=TuPasswordSeguro123!;encrypt=true;trustServerCertificate=true
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_cte
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/project-bd:/app
      - /app/node_modules